#[Info]
site_name: Postgraduate Entrance Examination Notes #your site name 显示在左上角
site_url: https://juanniaoxx.github.io/kaoyan-note
site_description: Content and ambitious, gentle yet firm.
site_author: Weary Bird # your name
#[UI]
theme:
  name: material
  custom_dir: docs/overrides #覆写路径
  # font: #谷歌字体，自行搜索
  #   text: Bitter  #文本字体
  #   code: Roboto Mono  #代码字体
  logo: http://www.huixueba.net/Content/WebImage/day_191009/201910091021452744_watermark.jpg #左上角logo，可插入图片链接

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      # teal 
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black 
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式

  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate
  language: zh # 一些提示性的文字会变成中文

  icon:
    repo: fontawesome/brands/github #右上角图标
    logo: logo
edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/juanniaoxx # 右上角点击跳转的链接
repo_name: Weary Bird # 右上角的名字

# [Navigtion]
nav:
  - 标签: tag.md
  - 考纲与笔记:
      - 考纲合集: 考纲/考纲.md 
      - 数学笔记: 考纲/数学笔记.md
      - 英语笔记:
          - 阅读:
              - 2005年阅读: 英语/阅读/2005.md
              - 2006年阅读: 英语/阅读/2006.md
              - 2007年阅读: 英语/阅读/2007.md
              - 2008年阅读: 英语/阅读/2008.md
              - 2009年阅读: 英语/阅读/2009.md
              - 2010年阅读: 英语/阅读/2010.md
              - 2011年阅读: 英语/阅读/2011.md
              - 2012年阅读: 英语/阅读/2012.md
              - 2013年阅读: 英语/阅读/2013.md
              - 2014年阅读: 英语/阅读/2014.md
              - 2015年阅读: 英语/阅读/2015.md
              - 2016年阅读: 英语/阅读/2016.md
              - 2017年阅读: 英语/阅读/2017.md
              - 2018年阅读: 英语/阅读/2018.md
              - 2019年阅读: 英语/阅读/2019.md
              - 2020年阅读: 英语/阅读/2020.md
              - 2021年阅读: 英语/阅读/2021.md
              - 2022年阅读: 英语/阅读/2022.md
              - 2023年阅读: 英语/阅读/2023.md
              - 2024年阅读: 英语/阅读/2024.md
              - 2025年阅读: 英语/阅读/2025.md
          - Monkey-外刊:
              - Text1-Text4: 英语/Monkey-锐读外刊/Text1-Text4.md
      - 政治笔记: 
          - 马克思主义基本原理: 考研政治/马克思主义基本原理.md
  - 错题集: 
          - 错题集: 错题集/错题集.md 
          - Total_PDF: 错题集/total.pdf 

  - 计算机基础(408):
    - 数据结构:
      - 绪论: 计算机基础/数据结构/chapter 1.md
      - 线性表: 计算机基础/数据结构/chapter 2.md
      - 栈,队列与数组: 计算机基础/数据结构/chapter 3.md
      - 串: 计算机基础/数据结构/chapter 4.md
      - 树与二叉树: 计算机基础/数据结构/chapter 5.md
      - 图与图算法: 计算机基础/数据结构/chapter 6.md
      - 查找: 计算机基础/数据结构/chapter 7.md
      - 排序: 计算机基础/数据结构/chapter 8.md
    - 计算机网络:
      - 绪论: 计算机基础/计算机网络/chapter 1.md
      - 数据通信基础: 计算机基础/计算机网络/chapter 2.md
      - 物理层: 计算机基础/计算机网络/chapter 3.md
      - 数据链路层: 计算机基础/计算机网络/chapter 4.md
      - 网络层: 计算机基础/计算机网络/chapter 5.md
      - 传输层: 计算机基础/计算机网络/chapter 6.md
      - 应用层: 计算机基础/计算机网络/chapter 7.md
    - 计算机组成原理:
      - 绪论: 计算机基础/计算机组成原理/chapter 1.md
      - 数据的表示和运算: 计算机基础/计算机组成原理/chapter 2.md
      - 存储系统: 计算机基础/计算机组成原理/chapter 3.md
      - 指令系统: 计算机基础/计算机组成原理/chapter 4.md
      - 中央处理器: 计算机基础/计算机组成原理/chapter 5.md
      - 总线: 计算机基础/计算机组成原理/chapter 6.md
      - 输入输出系统: 计算机基础/计算机组成原理/chapter 7.md
    - 操作系统:
      - 绪论: 计算机基础/操作系统/chapter 1.md
      - 进程和线程: 计算机基础/操作系统/chapter 2.md
      - 内存管理: 计算机基础/操作系统/chapter 3.md
      - 文件系统: 计算机基础/操作系统/chapter 4.md
      - 输入输出管理: 计算机基础/操作系统/chapter 5.md
  - 历年真题解析:
      - 数据结构大题: 计算机基础/数据结构/大题笔记.md
      - 计算机网络大题: 计算机基础/计算机网络/大题笔记.md
      - 计算机组成原理大题: 计算机基础/计算机组成原理/大题笔记.md
      - 操作系统大题: 计算机基础/操作系统/大题笔记.md


copyright: Copyright &copy; 2025~2026 Weary Bird # 左下角的版权声明

extra:
  generator: false #是否在页脚显示“使用 MkDocs 材料制造”

    # 网页底部反馈
  feedback:
    title: 此页面有帮助吗？
    ratings:
      - icon: material/thumb-up-outline #图标可自定义
        name: This page was helpful
        data: 1
        note: >-
          谢谢你的反馈！
      - icon: material/thumb-down-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! Help us improve this page by
          using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # cookies设置（可选）
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
  #     如果你同意,你可以帮助我们让我们的网站更好

plugins:
  - search #搜索配置
  - tags

markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  # 缩写词 语法为 *[HTML]: HyperText Markup Language 
  - abbr 
  # 运行为MarkDown元素添加HTML属性
  - attr_list
  # 支持警告/提示框 
  - admonition
  # 支持定义列表(类似<dl>)
  - def_list
  # 支持脚注 
  # 语法为 
  # 这是一个脚注[1](@ref) 
  # [1](@ref): 脚注内容
  - footnotes
  # 运行在HTML内嵌套markdown语法
  # <div markdown="1"> </div>
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret # 支持插入符(^)格式
  - pymdownx.betterem # 增强强调语法
  - pymdownx.critic #支持批判性标记 (增删改注释)
  - pymdownx.details  # 支持可折叠区域 
  - pymdownx.inlinehilite # 支持行内代码高亮
  - pymdownx.keys ## 支持渲染键盘按键
  - pymdownx.mark ## 支持标记文本 ==高亮== -> 高亮
  - pymdownx.snippets # 支持代码片段复用
  - pymdownx.smartsymbols # 将符号转换为特殊字符
  - pymdownx.tilde # 支持删除线

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件

  - pymdownx.arithmatex: # latex支持
      generic: true
      smart_dollar: false
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

extra_javascript:
  - javascripts/extra.js
  - javascripts/latex.js #自定义javascript
  - javascripts/mathjax.js #Latex支持
  # - https://polyfill.io/v3/polyfill.min.js?features=es6 #Latex支持
  - javascripts/favicons.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Latex支持
  # - ckplayer/js/ckplayer.js #播放器配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支持
  # - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了 

extra_css:
  - stylesheets/extra.css # 自定义CSS
  - stylesheets/link.css #友链配置
  - stylesheets/customize.css # 搜索圆角优化
  # - stylesheets/video.css #播放器可选配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalk支持
  # - ckplayer/css/ckplayer.css   #播放器配置
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支持
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支持

  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #字体
